### ISSUE TITLE
Hangs on "Reading Game Data"

### ISSUE THREAD

**Issue by Muirrum** [shawncplus/soma#10]
Exactly what the title says. The app just hangs on reading the data.

**Comment by Xalior** [comment]
You probably have some corrupt YML or similar. Open developer tools and see what the app says at startup/when reading data.

**Comment by Muirrum** [comment]
The package.json is missing the module js-yaml.

**Comment by Muirrum** [comment]
Which is still going on, even after I've installed it multiple times.

**Comment by shawncplus** [comment]
What's your actual stack trace? Soma doesn't need js-yaml in its package.json because it relies on the ranviermud repository for loading which is the one with the package. So one issue could be that you haven't run `npm install` in your ranviermud repo

**Comment by d3x0r** [comment]
THe directory selected was wron;g; edited main.js and enabled devtools.  Devtools reported it couldn't load 'src/Config' which isn't in Ranviermud, but in Ranviermud/node_modules/ranvier (/src/Config) but when I select THAT directory, it says there are no bundles.

**Comment by Muirrum** [comment]
I managed to get it to work after rerunning `npm install` in both repos.

**Comment by d3x0r** [comment]
and then selecting what as the `Specify your Ranvier repo directory` ?
My directory structure is 
/home/d3x0r/work/mud/
  - ranviermud (.git)
     - npm install
     - npm run init
     - npm run start ... mud server starts, and is able to be connected to.
  - soma (.git)
     - npm install

  - Neuro (.git)

using ranviermud
internal/modules/cjs/loader.js:602 Uncaught Error: Cannot find module '/home/d3x0r/work/mud/ranviermud/src/Config'

using ranviermud/node_modules/ranvier (which has src/Config)
then I get a popup 

![image](https://user-images.githubusercontent.com/1909610/53427989-cdb02580-399e-11e9-8d19-f08d43484e8d.png)

all up to date.  Arch linux.  Electron installs with system package manager.

**Comment by Muirrum** [comment]
I selected the root ranviermud directory (with .git and ranvier script)
